spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: tester
    password: passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
