apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zoo"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zookeeper
      annotations:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: mjkong/zookeeper:2019.03.16
        env:
        - name: KAFKA_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/conf/log4j.properties
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: leader-election
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 120Mi
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '[ "imok" = "$(echo ruok | nc -w 1 127.0.0.1 2181)" ]'
        volumeMounts:
        - name: configmap
          mountPath: /etc/kafka
        - name: sharedvolume
          mountPath: /data
      volumes:
      - name: configmap
        configMap:
          name: zookeeper-config
  volumeClaimTemplates:
  - metadata:
      name: sharedvolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: kafka-broker
      selector:
        matchLabels:
          app-role: pv
          app-type: zk
      resources:
        requests:
          storage: 3Gi
