---
apiVersion: v1
kind: Service
metadata:
  name: hq-ca
  labels:
    run: hq-ca
spec:
  type: NodePort
  selector:
    name: hq-ca
  ports:
  - protocol: TCP
    nodePort: 30054
    targetPort: 7054
    port: 30054
    name: grpc
